### PR TITLE
Add echart examples

### PR DESCRIPTION
**Pull request by dfordivam**

### CODE REVIEW

**Comment by antislava** [comment]
@dfordivam Wanted to try this but getting this error (with `nix-build -A exe --show-trace`):
```
getting attributes of path 'reflex-examples/deps/reflex-dom-echarts': No such file or directory                            
```
Is deps folder actually committed?

**Comment by dfordivam** [comment]
@antislava oops forgot that.. please try again..

**Comment by antislava** [comment]
@dfordivam Seems to work great, thanks! (checked nix-build as well - did take a while to compile:))

**Review by luigy — APPROVED** [review]
lgtm once warnings are fixed

**Comment by luigy** [comment]
Thanks!

**Pull request merged**
